GET http://localhost:8080/api/artists/


###
GET http://localhost:8080/api/artists/1/



###

POST http://localhost:8080/api/artists/add/
Content-Type: application/json

{
  "artistName": "Another New Test Artist",
  "imageUrl": "www.testUrl2.com"
}


###

PATCH http://localhost:8080/api/artists/1/addAlbum/
Content-Type: application/json

{
  "albumName": "First Test Album",
  "recordLabel": "Sony",
  "imageUrl": "Albmum Image.com"
}


###
DELETE http://localhost:8080/api/artists/delete/1/