GET http://localhost:8080/api/songs/

###

GET http://localhost:8080/api/songs/4/


###

PATCH http://localhost:8080/api/songs/8/addComment/
Content-Type: application/json

{
  "authorName": "Nick",
  "text": "Nick added one more comment "
}

###
DELETE http://localhost:8080/api/songs/delete/6/
